import { fonts } from '@/fonts';
import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={fonts.rubik.variable}>
			<body>
				<ChakraProvider>
					<main>{children}</main>
				</ChakraProvider>
			</body>
		</html>
	);
}
