import { fonts } from '@/fonts';
import { ChakraProvider } from '@/providers/ChakraProvider';
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';
import { Box } from '@chakra-ui/react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={fonts.rubik.variable}>
			<body>
				<ChakraProvider>
					<ReactQueryProvider>
						<Box as="main" py={16}>
							{children}
						</Box>
					</ReactQueryProvider>
				</ChakraProvider>
			</body>
		</html>
	);
}
